### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by robjob1984** [adaptris/interlok-json#212]
> Task :interlok-jq:compileJava
Note: C:\Users\Rob.Whitestone\Downloads\interlok-json-develop\interlok-jq\src\main\java\com\adaptris\core\json\jq\JsonJqTransform.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :interlok-jq:generateVersion FAILED
fatal: not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Rob.Whitestone\Downloads\interlok-json-develop\build.gradle' line: 75

* What went wrong:
Execution failed for task ':interlok-jq:generateVersion'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
2 actionable tasks: 2 executed

**Comment by quotidian-ennui** [comment]
- If you're trying to compile using a source download, it will fail, because generating version numbers relies on it being a git repo
    - this is related to  "buildInfo()" generation.
- Gradle-7.x upgrade is a known issue.
